version: '2'

services:

  udp-packet-forwarder:
    
    image: rakwireless/udp-packet-forwarder:latest
    container_name: udp-packet-forwarder
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - ./global_conf.json:/app/global_conf.json:ro
      - 'pktfwdr:/var/pktfwd'
    devices:
      - '/dev/spidev1.0:/dev/spidev32766.0'
    
    environment:
      CONCENTRATOR: "SX1301"
      INTERFACE: "SPI"
      HAS_GPS: "0"
      HAS_LTE: "0"
      RESET_GPIO: 149
      RADIO_DEV: "/dev/spidev32766.0"
      TTN_REGION: "nam1"
      SERVER_HOST: 10.10.130.129
      SERVER_PORT: 1680
      BAND: "us_902_928"

volumes:
  pktfwdr: {}


